package com.taxiandcabservice.accessing_data_mysql.controllers;

import com.taxiandcabservice.accessing_data_mysql.auth.*;
import com.taxiandcabservice.accessing_data_mysql.users.Passenger;
import com.taxiandcabservice.accessing_data_mysql.users.PassengerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@RestController // This means that this class is a Controller
@RequestMapping(path = "/api") // This means URL's start with /demo (after Application path)
public class PassengerController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PassengerRepository passengerRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private JwtUtil jwtUtil;

    @PostMapping(path = "/passenger/auth/register")
    public Passenger addPassenger(@RequestBody RegisterRequest registerRequest) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Passenger n = new Passenger();
        n.setName(registerRequest.getName());
        n.setEmail(registerRequest.getEmail());
        n.setPassword(passwordEncoder.encode(registerRequest.getPassword()));
        passengerRepository.save(n);
        return n;
    }

    @PostMapping(path = "/passenger/auth/login")
    public TokenResponse login(@RequestBody LoginRequest request) {
        TokenResponse token = new TokenResponse();

        //Verify user is in DB
        Optional<Passenger> opPassenger = passengerRepository.findByEmail(request.getEmail());
        if (opPassenger.isPresent()) {

            if (passwordEncoder.matches(request.getPassword(), opPassenger.get().getPassword())) {
                token.setSuccess(true);
            }
        }

        if (token.isSuccess()) {
            token.setToken(jwtUtil.generateToken(opPassenger.get().getName()));
            token.setRole("PASSENGER");
        }
        else {
            token.setError("Invalid Username or Password");
        }
        return token;
    }

    @PostMapping(path = "/passenger/auth/test")
    public String TestMethod() {
        return "test";
    }

    @GetMapping(path = "/passenger/{id}")
    public Optional<Passenger> getPassenger(@PathVariable Integer id) {
        // This returns a JSON or XML with the users
        return passengerRepository.findById(id);
    }

//    @PatchMapping

}
