#spring.application.name=taxicabservice
#
#spring.datasource.url=jdbc:mysql://avnadmin:AVNS_YywZpMTi2o4UEF1mKNl@taxicabservicedatabase-taxicabservicedatabase.i.aivencloud.com:21605/defaultdb?ssl-mode=REQUIRED
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_YywZpMTi2o4UEF1mKNl
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.docker.compose.enabled=false

spring.profiles.active=devnot
spring.main.allow-bean-definition-overriding=true
# For quick testing -- also remove filter bypasses when deploying

spring.datasource.url=jdbc:h2:file:./data/db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

server.port=8090